### ISSUE TITLE
Add more derive to types?

### ISSUE THREAD

**Issue by George-Miao** [slawlor/ractor#91]
When using types like `factory::Job`, it is impossible to clone it due to lack of derives. It will be useful to add them. If this is desirable, I can make a PR.

**Comment by slawlor** [comment]
That's kind-of by design, as the actor should "own" the job and we want to move ownership vs cloning everywhere.

Do you have a use-case you're trying to solve by cloning a job? The underlying message type can be cloned, since it's up to the developer to define it, and then you could re-create the job options. But I don't really see the need to clone the full job itself.

**Comment by George-Miao** [comment]
> That's kind-of by design, as the actor should "own" the job and we want to move ownership vs cloning everywhere.
> 
> 
> 
> Do you have a use-case you're trying to solve by cloning a job? The underlying message type can be cloned, since it's up to the developer to define it, and then you could re-create the job options. But I don't really see the need to clone the full job itself.

This makes sense. I actually couldn't remember why I need it to be clone.
