### ISSUE TITLE
Production. (Actix).

### ISSUE THREAD

**Issue by uwejan** [slawlor/ractor#94]
Hey there, I am coming from actix actors background, Suffering from some limitations, and I on search for an alternative or an easy convert.

I am going to state down my use case, and I wonder if it will be feasible to make the convert upon your answers. It is also good to know if the crate is being used on production.

1. Websocket actor, handle read/write. With actix simple as ctx.addStream(), then implement the message types, for write add write part of the stream to the sate of the actor, and calling when needed.
2. Db actor, handle db operations. here comes majore suffering with async/await/blocking thread ..etc, will share a snippets at the end.
3. Also using tauri, so the runtime enviroment has to be shared, where as had a blummer back in while to figure actix runtime fix to make it work, which is still not compelling.
4. some cpu intensive actors dealing with file system on seperate threads.
5. back to 4 where as cross actor comunication through recipients or actor refs.

Not going to mention supervisoring as I already read that it is there.
Making the move to an already crate or using pure rust / tokio channels is the way to go for this project of mine, but knwoing a crate already has the potentials to solve the issues am facing will just make things easier, It will come at the end how much time the conversion of the project will take. So your answers are really important.

Thank you.

Blocking thread. // lack of async/await support.
I also tried atomicResponse but in that case I losse access to self, and being static issues.
Not trying to figure out a fix, as moving forward async/await is the future to go.
```
impl Handler<DbOperations> for McActor {
    type Result = String;
    //type Result = ResponseFuture<String>;
    fn handle(&mut self, msg: DbOperations, ctx: &mut Self::Context) -> Self::Result {
        return match msg {
             DbOperations::Get { key } => {
               block_on(async {
                    sqlx::query_as::<_, DbOperationValues>(select_query)
                        .bind(key)
                        .fetch_one(self.db.as_ref().unwrap())
                        .await
                        .unwrap()
                }).value
                 
            }
            DbOperations::Set { key, value } => {   
                block_on(async {
                    sqlx::query_as::<_, DbOperationValues>(insert_query)
                        .bind(key)
                        .bind(value)
                        .fetch_one(self.db.as_ref().unwrap())
                        .await
                        .unwrap()
                }).value
            }
        };
    }
}
```

**Comment by slawlor** [comment]
So there's a lot here, and if you find an answer isn't clear, let me know and I'll try and clarify it.

* `ractor` is fully async-await in it's handlers, including startup and shutdown routines
* As you mentioned, we do have supervision but probably a bit of a different syntax than `actix` from my understanding

1. For web-sockets style use-case, we would create child actors which are each responsible for read and write separately. The parent actor is then your multiplexor, so you interact with that for fully-structured frames (or objects if you want to handle serialization in those layers). An example is our [network session handler](https://github.com/slawlor/ractor/blob/main/ractor_cluster/src/net/session.rs) in `ractor_cluster`. This could probably be added as a wrapped helper, but unlike `actix` we don't have a "context" here which can interact with.
2. For a database actor, we already are async handlers so you should be good-to-go out of the box
3. Since `tauri` is built on `tokio` it "should" work fine. But I'm not that familiar with `tauri` so you'd need to try it.
4. So for thread-blocking work, I'd recommend using [`tokio::task::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) to push onto CPU-bound tasks to not block the main runtime executor. This yields a `JoinHandle` which you can await on within the normal `tokio` Task inside the actor's handler. The linked examples from tokio show waiting on a blocking task without blocking the high-performance threads.
5. We have `ActorRef<TMessage>` (after the open PR merges #89)
