### ISSUE TITLE
Get notified if node disconnects/shuts down

### ISSUE THREAD

**Issue by xunafay** [slawlor/ractor#98]
Is there a way to get notified if a node becomes unavailable?
I'd like to try reconnecting when a node has to restart or network is not reliable

**Comment by slawlor** [comment]
This might be worth adding some "Node events" channel on the `NodeServer` actor. Such that you could subscribe to node change events.

**Comment by xunafay** [comment]
I'd love to try to implement this but I'm still a bit of a rusty novice. So if I open a PR for this feel free to give it a healthy dose of criticism

**Comment by xunafay** [comment]
I've identified that https://github.com/slawlor/ractor/blob/d79ea281cbd8af26cd3416c085a60bf3a56fc44c/ractor_cluster/src/node/mod.rs#L434 would be the place to emit an event

I was just wondering what you thought would be the best channel/method to notify any listeners to these events? @slawlor

**Comment by slawlor** [comment]
You could use something like an output port, but their syntax still isn't ideal to me (it's the least "clean" aspect of `ractor` imho right now). Otherwise I'd say a "broadcast" actor would make sense. It's message structure might look like

```rust
enum BroadcastMessage<TMessage, F> 
// this function is what actually sends the message to the subscribing actor
where F: Fn(ActorCell, TMessage) -> () + 'static, 
{
  Subscribe(ActorCell, F),
  SendMessage(TMessage),
}
```

There's probably some weird lifetime stuff, but I "think" this would work?
